"""Ajout de la colonne last_killed_at dans bounties

Revision ID: 02a49a8548fd
Revises: 826fa1e505f3
Create Date: 2025-01-14 15:42:27.275856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a49a8548fd'
down_revision = '826fa1e505f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_killed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.drop_column('last_killed_at')

    # ### end Alembic commands ###
