"""Ajout des champs aux recherchés

Revision ID: 02b0873cff69
Revises: 912f90a39430
Create Date: 2025-01-14 01:09:14.918002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b0873cff69'
down_revision = '912f90a39430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('links', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('spot', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('map', sa.String(length=255), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=512), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('map')
        batch_op.drop_column('spot')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('icon')
        batch_op.drop_column('links')

    # ### end Alembic commands ###
