"""Ajout de la colonne user_id à la table recipes

Revision ID: 14587d470750
Revises: 275c3c9bf568
Create Date: 2025-01-01 18:04:56.443174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14587d470750'
down_revision = '275c3c9bf568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
