"""Ajout du modèle TrackedResources et autres modifications

Revision ID: 6882f016d2a5
Revises: 9ba385ebbb96
Create Date: 2025-01-02 12:23:01.843271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6882f016d2a5'
down_revision = '9ba385ebbb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_resources', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_resource', ['user_id', 'resource_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_resources', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_resource', type_='unique')

    # ### end Alembic commands ###
