"""Adding tracking table

Revision ID: d18f24a58ac7
Revises: d0e04eb988fd
Create Date: 2025-01-02 22:12:56.386886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18f24a58ac7'
down_revision = 'd0e04eb988fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('component_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('unique_user_resource', type_='unique')
        batch_op.drop_column('resource_name')
        batch_op.drop_column('date_tracked')
        batch_op.drop_column('resource_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('date_tracked', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('resource_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.create_unique_constraint('unique_user_resource', ['user_id', 'resource_id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('component_name')
        batch_op.drop_column('component_id')

    # ### end Alembic commands ###
