"""Ajout de la table tracked_resources

Revision ID: e79afdf8544e
Revises: ef8788ca7793
Create Date: 2025-01-01 20:03:31.797694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79afdf8544e'
down_revision = 'ef8788ca7793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_resources', schema=None) as batch_op:
        batch_op.drop_column('current_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_price', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
